
###home
GET http://localhost:3000/api/home HTTP/1.1
content-type: application/json
Authorization: Bearer superman


###signup

POST http://localhost:3000/api/signup HTTP/1.1
content-type: application/json
Authorization: Bearer superman

["hulk","123"]
 


###login
POST http://localhost:3000/api/login HTTP/1.1
content-type: application/json
Authorization: Bearer superman

["batman","123"]

###updateuser

POST http://localhost:3000/api/updateuser HTTP/1.1
content-type: application/json
Authorization: Bearer superman

{
    "id":2,
    "username":"batman",
    "passwd":"123",
    "new_username":"batman",
    "new_passwd":"123"
}

###deleteuser

DELETE http://localhost:3000/api/deleteuser HTTP/1.1
content-type: application/json
Authorization: Bearer superman

{
    "id":2,
    "username":"batman",
    "passwd":"123"
}

###sessionverification

POST http://localhost:3000/api/sessionverification HTTP/1.1
content-type: application/json
Authorization: Bearer superman

["e129b4f7d75ff4d4fcfa806e432d08d8b808049a0fd00240252f45598ce9f82b"]


###updatesession

POST http://localhost:3000/api/updatesession HTTP/1.1
content-type: application/json
Authorization: Bearer superman

[2]