# services:
#   mysqldb:
#     image: mysql:8.0
#     container_name: mysqlcontainer
#     command: --default-authentication-plugin=mysql_native_password
#     restart: unless-stopped
#     volumes:
#       - ./databaseinit/login.sql:/docker-entrypoint-initdb.d/0_init.sql
#       - ./dbtemp:/var/lib/mysql
#     ports:
#       - 3306:3306
#     expose:
#       - 3306
#     environment:
#       MYSQL_DATABASE: logindb
#       MYSQL_USER: admin
#       MYSQL_PASSWORD: letmein
#       MYSQL_ROOT_PASSWORD: letmeinroot
#       SERVICE_TAGS: prod
#       SERVICE_NAME: mysqldb
#     networks:
#       - internalnet
# networks:
#   internalnet:
#     driver: bridge


# version: '3'

# services:
#   mysqldb:
#     image: mysql:8.0
#     container_name: mysqlcontainer
#     command: --default-authentication-plugin=mysql_native_password
#     restart: unless-stopped
#     volumes:
#       - ./databaseinit/login.sql:/docker-entrypoint-initdb.d/0_init.sql
#       - ./datatemp:/var/lib/mysql
#     ports:
#       - 3306:3306
#     expose:
#       - 3306
#     environment:
#       MYSQL_DATABASE: logindb
#       MYSQL_USER: admin
#       MYSQL_PASSWORD: letmein
#       MYSQL_ROOT_PASSWORD: letmeinroot
#       SERVICE_TAGS: prod
#       SERVICE_NAME: mysqldb
#     networks:
#       - internalnet

# networks:
#   internalnet:
#     driver: bridge

    
#custom idea

# version: '3.8'

# services:
#   app:
#     image: auth0.1
#     ports:
#       - "3000:3000"
#     environment:
#       SERVER_PORT: 3000
#       SERVER_PASSWORD: superman
#       JWT_PASSWORD: supermancantbeatbatman
#       JWT_REFRESS_PASSWORD: ironman
#       DB_HOST: mysqldb
#       DB_PORT: 3306
#       DB_USER: admin
#       DB_PASSWORD: letmein
#       DB_DATABASE: logindb
#       DB_CONNECTIONLIMIT: 10
#       DB_QUEUELIMIT: 10
#     depends_on:
#       - mysqldb
#     networks:
#       - internalnet

#   mysqldb:
#     image: mysql:8.0
#     container_name: mysqlcontainer
#     command: --default-authentication-plugin=mysql_native_password
#     restart: unless-stopped
#     volumes:
#       - ./databaseinit/login.sql:/docker-entrypoint-initdb.d/0_init.sql
#       - ./dbtemp:/var/lib/mysql
#     ports:
#       - "3306:3306"
#     expose:
#       - "3306"
#     environment:
#       MYSQL_DATABASE: logindb
#       MYSQL_USER: admin
#       MYSQL_PASSWORD: letmein
#       MYSQL_ROOT_PASSWORD: letmeinroot
#       SERVICE_TAGS: prod
#       SERVICE_NAME: mysqldb
#     networks:
#       - internalnet

# networks:
#   internalnet:
#     driver: bridge


#not expose my sql

version: '3.8'

services:
  app:
    image: auth0.1
    ports:
      - "3000:3000"
    environment:
      SERVER_PORT: 3000
      SERVER_PASSWORD: superman
      JWT_PASSWORD: supermancantbeatbatman
      JWT_REFRESS_PASSWORD: ironman
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: letmein
      DB_DATABASE: logindb
      DB_CONNECTIONLIMIT: 10
      DB_QUEUELIMIT: 10
    depends_on:
      - mysqldb
    networks:
      - internalnet

  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./databaseinit/login.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./dbtemp:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: logindb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmeinroot
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
