services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./databaseinit/login.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./dbtemp:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: logindb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmeinroot
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge


# version: '3'

# services:
#   mysqldb:
#     image: mysql:8.0
#     container_name: mysqlcontainer
#     command: --default-authentication-plugin=mysql_native_password
#     restart: unless-stopped
#     volumes:
#       - ./databaseinit/login.sql:/docker-entrypoint-initdb.d/0_init.sql
#       - ./datatemp:/var/lib/mysql
#     ports:
#       - 3306:3306
#     expose:
#       - 3306
#     environment:
#       MYSQL_DATABASE: logindb
#       MYSQL_USER: admin
#       MYSQL_PASSWORD: letmein
#       MYSQL_ROOT_PASSWORD: letmeinroot
#       SERVICE_TAGS: prod
#       SERVICE_NAME: mysqldb
#     networks:
#       - internalnet

# networks:
#   internalnet:
#     driver: bridge

    
