CREATE DATABASE IF NOT EXISTS logindb;

USE logindb;

DROP TABLE IF EXISTS loginlist;

CREATE TABLE loginlist(
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWDHASH VARCHAR(128) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LASTLOGIN_AT DATE,
    UPDATED_AT DATE,
    PRIMARY KEY (ID),
    CONSTRAINT UQ_LOGIN_USERNAME UNIQUE (USERNAME)
)

